---
# boto3 is used by some Ansible AWS tasks (when run on the host)
- name: Install boto3
  ansible.builtin.pip:
    name:
      - boto3
      - botocore
    state: latest
  become: true

# enable Ansible to sudo as unprivileged user
- name: Install sudo & acl
  ansible.builtin.apt:
    pkg:
      - sudo
      - acl
    state: latest
  become: true

# enable ansible unzip module, as well as embedded unzip
# such as get_url
- name: Install unzip
  ansible.builtin.apt:
    pkg:
      - unzip
      - gzip
    state: latest
  become: true

- name: Install cron for daily jobs
  ansible.builtin.apt:
    pkg: cron
    state: latest
  become: true

- name: Install terminal editors
  ansible.builtin.apt:
    pkg: nano
    state: latest
  become: true

# enable server to be used as relay point for other IPs
- name: Install sshpass
  ansible.builtin.apt:
    pkg: sshpass
    state: latest
  become: true