---
- name: Deploy system resolv.conf
  copy:
    src:  dns-quad9-resolv.conf
    dest: /etc/resolv.conf
  become: true

- name: Check internet connectivity
  wait_for: host=google.com port=80 timeout=10
