---
- name: Deploy system resolv.conf
  ansible.builtin.copy:
    src:  dns-quad9-resolv.conf
    dest: /etc/resolv.conf
  become: true

- name: Check internet connectivity
  ansible.builtin.wait_for:
    host: google.com
    port: 80
    timeout: 10
