---
- name: Install python3-pip
  apt:
    pkg:
      - virtualenv
      - python3-setuptools
      - python3-pip
    state: latest
  become: true

- name: Upgrade pip
  pip:
    name: pip
    state: latest
  become: true
